### ISSUE TITLE
Add linters for the project

### ISSUE THREAD

**Issue by sloboegen** [vickumar1981/pyeffects#24]
What do you think about adding several popular linters/formatters for this project, i.e. [isort](https://pycqa.github.io/isort/), [black](https://github.com/psf/black), [flake8](https://flake8.pycqa.org/en/latest/) (or [ruff](https://github.com/astral-sh/ruff))?

Also, do you want to migrate to poetry from pipenv/tox/...?

**Comment by vickumar1981** [comment]
@sloboegen   :+1: 

i'd like to use black b/c i think it encompasses what flake + pylint were doing before.

for dependency management, i'd really like to use `pdm`: https://github.com/pdm-project/pdm

But, I'm also okay with using poetry if you think that's an easier approach.

Thanks for opening up this issue.

**Comment by vickumar1981** [comment]
Updated to using black as part of: https://github.com/vickumar1981/pyeffects/pull/34
