### ISSUE TITLE
Add __str__ method to classes that can be initialized

### ISSUE THREAD

**Issue by vickumar1981** [vickumar1981/pyeffects#3]
Most of the classes already have an `__repr__` for printing/debugging, but should move this to a `__str__` method and have the repr function just call the str function.

**Comment by BattiniSandeep** [comment]
Hey, I'm new to this project and to open source. Would like to solve this issue. could you please assign this to me? Thanks

**Comment by vickumar1981** [comment]
@BattiniSandeep   it's assigned to you now.  thanks!

**Comment by BattiniSandeep** [comment]
Hii @vickumar1981, I have made few changes to code. But while pushing the code, I'm getting the following error. 

ERROR: Permission to vickumar1981/pyeffects.git denied to BattiniSandeep.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

I have browsed google about this error, but most of them are saying to create ssh key and add to github. But still after doing that I'm facing this error. Let me know igf you have any idea about this

**Comment by BattiniSandeep** [comment]
Raised pr. please have a look and let me know. Thanks

**Comment by vickumar1981** [comment]
Addressed by: https://github.com/vickumar1981/pyeffects/pull/28
