### ISSUE TITLE
Add `__eq__` so classes can be compared for equality

### ISSUE THREAD

**Issue by vickumar1981** [vickumar1981/pyeffects#4]
All implemented classes need to have a dunder  `__eq__` method so that they can be compared for equality.

**Comment by BattiniSandeep** [comment]
Would like to work on this. Can you please assign this to me. Thanks

**Comment by BattiniSandeep** [comment]
@vickumar1981 I think below are the classes which need __eq__. 

- Left
- Right
- Future
- Some
- Empty
- Failure
- Success

Let me know if I miss anything.

**Comment by vickumar1981** [comment]
@BattiniSandeep   looks about right.  thanks again!!

**Comment by BattiniSandeep** [comment]
Hii @vickumar1981 I have raised a pr, It addresses all the classes except Future. Please have look at it. Thanks

**Comment by vickumar1981** [comment]
Resolved by: https://github.com/vickumar1981/pyeffects/pull/34
